"use client";

import './globals.css';
import Head from 'next/head';
import store from '@/provider/store';
import { Provider } from 'react-redux';
import 'react-phone-input-2/lib/style.css';
import { GoogleOAuthProvider } from '@react-oauth/google';

const clientId = process.env.NEXT_PUBLIC_CLIENT_ID

// export const metadata = {
//   title: 'Zee invoices',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Zee Invoice</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <body>
        <GoogleOAuthProvider clientId={clientId}>
          <Provider store={store}>
            {children}
          </Provider>
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}